name: Issue test
on: [issues, workflow_dispatch]
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: Print issue details
              run: echo "${{toJSON(github.workflow)}}"
