name: Issue test
on: [issues, workflow_dispatch]
jobs:
    output-info:
        runs-on: ubuntu-latest
        steps:
            - name: Print issue details
              run: echo "${{toJSON(github.event)}}"
