name: Test project
on: push
jobs:
    lint_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Install dependencies
              uses: npm ci
            - name: Lint project
              uses: npm lint
            - name: Run test
              uses: npm test
    build:
        runs-on: ubuntu-latest
        needs: lint_test
        steps: 
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Install dependencies
              uses: npm ci
            - name: Build project
              uses: npm run build
            - name: Print after completion
              uses: echo "Complete lint test and build"


    