name: Test project
on: push
jobs:
    lint_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint project
              run: npm run lint
            - name: Run test
              run: npm run test
    build:
        runs-on: ubuntu-latest
        needs: lint_test
        steps: 
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Print after completion
              run: echo "Complete lint test and build"


    